apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: social-archive
  namespace: default
spec:
  cluster:
    name: ossway-pg
  databaseReclaimPolicy: retain
  ensure: present
  name: social_archive
  owner: app
