apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "social-archive.fullname" . }}-config
  labels:
    {{- include "social-archive.labels" . | nindent 4 }}
data:
  BACKEND_URL: "http://{{ include "social-archive.fullname" . }}-backend:8000"
