"""Static mapping of TRUST sector codes to operator names.

Source: https://wiki.openraildata.com/index.php/TOC_Codes
The "Sector Code" column is the numeric code used in TRUST messages.
"""

TOC_NAMES: dict[str, str] = {
    "02": "JSD Rail Research & Development",
    "03": "Victa Westlink Rail",
    "04": "DB Cargo Charters",
    "05": "DB Cargo Freight",
    "06": "Eurostar",
    "07": "Rail Operations Group",
    "08": "DB Cargo International",
    "09": "Freightliner Intermodal",
    "10": "Serco Rail Operations",
    "11": "Freightliner Heavy Haul",
    "12": "Grand Union Trains",
    "13": "Europorte Channel",
    "15": "Network Rail (On-Track Machines)",
    "16": "LORAM",
    "17": "Hanson & Hall Rail Services",
    "18": "Swanage Railway",
    "19": "South Yorkshire Supertram",
    "20": "TransPennine Express",
    "21": "Greater Anglia",
    "22": "Grand Central",
    "23": "Northern Trains",
    "24": "Heathrow Connect",
    "25": "Great Western Railway",
    "27": "CrossCountry",
    "28": "East Midlands Railway",
    "29": "West Midlands Trains",
    "30": "London Overground",
    "31": "Network Rail Virtual Freight",
    "33": "Elizabeth line",
    "34": "DC Rail",
    "35": "Caledonian Sleeper",
    "36": "Vintage Trains",
    "37": "Seco Rail",
    "38": "Carillion Rail CTRL",
    "39": "Harsco",
    "40": "Balfour Beatty Rail",
    "42": "Colas Rail",
    "43": "Amey Fleet Services",
    "44": "Carillion Rail",
    "45": "Lumo",
    "46": "SB Rail",
    "49": "VolkerRail",
    "50": "West Coast Railways",
    "51": "North Yorkshire Moors Railway",
    "52": "Pre Metro Operations",
    "53": "SNCF Freight Services",
    "54": "GB Railfreight",
    "55": "Hull Trains",
    "56": "Nexus (Tyne & Wear Metro)",
    "57": "Go-Op",
    "59": "On Route Logistics",
    "60": "ScotRail",
    "61": "London North Eastern Railway",
    "62": "Fishbone Solutions",
    "64": "Merseyrail",
    "65": "Avanti West Coast",
    "71": "Transport for Wales",
    "72": "Legge Infrastructure Services",
    "79": "c2c",
    "80": "Southeastern",
    "84": "South Western Railway",
    "85": "Island Lines",
    "86": "Heathrow Express",
    "88": "Govia Thameslink Railway",
    "89": "Locomotive Services",
    "90": "LUL District Line (Wimbledon)",
    "91": "LUL Bakerloo Line",
    "92": "Network Rail Reserved Pathings",
    "93": "LUL District Line (Richmond)",
    "94": "Ffestiniog Railway",
    "95": "Varamis Rail",
    "97": "Direct Rail Services",
    "98": "Internal Testing",
}


def toc_name(toc_id: str | None) -> str:
    """Return the operator name for a TRUST sector code, or 'TOC <id>' if unknown."""
    if toc_id is None:
        return "Unknown"
    return TOC_NAMES.get(toc_id.strip(), f"TOC {toc_id}")
